### ISSUE TITLE
We should accept any `Tables`-compatible table as input, instead of only accepting `DataFrame`s

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/PreprocessMD.jl#24]
`Tables` refers to the [Tables.jl](https://github.com/JuliaData/Tables.jl) package.

---

We should accept any `Tables`-compatible table as input, instead of only accepting `DataFrame`s.

If the input is already a `DataFrame`, there's nothing extra we need to do. If the input is not a `DataFrame`, check if it is a `Tables`-compatible table. If it isn't a `Tables`-compatible table, throw an error. If it is a `Tables`-compatible table, convert it to a `DataFrame`.

Here is some example code.

```julia
using DataFrames: DataFrame
import Tables

function my_cool_function(df::DataFrame)
    # do stuff
end

function my_cool_function(input_object)
    assert_is_table(input_object)

    # convert `input_object` to a `DataFrame`
    df = DataFrame(input_object)::DataFrame

    # Assert that `df` is in fact a `DataFrame`
    df::DataFrame

    return my_cool_function(df)
end

function assert_is_table(x)
    if !Tables.istable(x)
        msg = "Input must be a table, but $(typeof(x)) is not a table"
        throw(ArgumentError(msg))
    end
    return nothing
end
```

**Comment by AshlinHarris** [comment]
#40
