### ISSUE TITLE
Documentation action fails

### ISSUE THREAD

**Issue by AshlinHarris** [bcbi/PreprocessMD.jl#60]
The documentation action fails if any functions aren't included in the docs. However, `Documenter.jl` pulls from the remote repo, so functions cannot be added until they exist in the main repo.

**Comment by DilumAluthge** [comment]
This isn't quite correct. The docs are built from the PR branch, so there's no chicken/egg issue here. You just need to make sure that all of your docstrings show up somewhere in the manual.

**Comment by AshlinHarris** [comment]
Oh, my mistake! I was testing by building the docs locally. Thank you!
