### ISSUE TITLE
Support String and other formats for column names as function inputs

### ISSUE THREAD

**Issue by AshlinHarris** [bcbi/PreprocessMD.jl#80]
Currently, only Symbols are supported

**Comment by DilumAluthge** [comment]
Actually, I would recommend that we standardize on a single type for column names, to reduce confusion and ambiguity.

DataFrames.jl uses `Symbol`s for column names, so for consistency with them, I would say that we should only support `Symbol`s for column names.

If users have their column names in another type, they are responsible for converting those column names to `Symbol`s.

**Comment by AshlinHarris** [comment]
DataFrames.jl supports column access by either `Symbol` or `String`. In pull request #101, I've removed the type restriction from the function definitions.

However, DataFrames.jl throws an `ArgumentError` if these are mixed, while this is handled under the hood by PreprocessMD.jl. This may or may not be a good thing, so I opened up issue #102 to discuss.

**Comment by DilumAluthge** [comment]
Let's do exactly what DataFrames does. So the user can give strings or symbols, but we throw an error if the two are mixed.

**Comment by AshlinHarris** [comment]
Sure, I'll go ahead with that.

https://github.com/bcbi/PreprocessMD.jl/issues/102#issuecomment-1145090115
